{{- if .Values.serviceAccount.enable }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "datagrok.fullname" . }}-sa
  labels:
  {{- include "datagrok.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}

{{- end }}